/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContourMap: typeof import('./src/components/ContourMap.vue')['default']
    copy: typeof import('./src/components/LeafletMap copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/test.vue')['default']
    TestTable: typeof import('./src/components/TestTable.vue')['default']
  }
}
