/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CesiumDistributeMap: typeof import('./src/components/CesiumDistributeMap.vue')['default']
    CesiumMap: typeof import('./src/components/CesiumMap.vue')['default']
    CesiumMapList: typeof import('./src/components/CesiumMapList.vue')['default']
    ContourMap: typeof import('./src/components/ContourMap.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    LeafletDistributeMap: typeof import('./src/components/LeafletDistributeMap.vue')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    LeafletMapList: typeof import('./src/components/LeafletMapList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleMap: typeof import('./src/components/SimpleMap.vue')['default']
    TestTable: typeof import('./src/components/TestTable.vue')['default']
    VerticalToolbar: typeof import('./src/components/VerticalToolbar.vue')['default']
  }
}
